### ISSUE TITLE
Error refreshing connections: "null"

### ISSUE THREAD

**Issue by shanecav84** [taskforcesh/issues#195]
I added a new queue with a worker and a recurring job and wanted to see its status in Taskforce. Our logs show that the the queue is being created and the worker started correctly. The existing queues are showing and refreshing them doesn't cause an error. When I use the refresh button in the sidebar, it shows a pop up with the message 'Error refreshing connections: "null"'

**Comment by manast** [comment]
I wonder, is this refresh done on a connection that is part of a team or a connection belonging to a user?

**Comment by manast** [comment]
What role do you have in the team?

**Comment by manast** [comment]
This should be resolved by now, just refresh the webpage and try to refresh the connection itself. Let me know if it works for you.

**Comment by neeraj-shetty** [comment]
Hey @manast 
We're still encountering issues with refreshing the connection.
We get the "Error refreshing connections" error even after refreshing the webpage

**Comment by manast** [comment]
Ok, looking into it.

**Comment by manast** [comment]
We have deployed a fix that should have resolved this issue.

**Comment by shanecav84** [comment]
It's now working. Thank you!
