### ISSUE TITLE
Internal Server Error when providing password

### ISSUE THREAD

**Issue by TimP4w** [taskforcesh/issues#22]
I keep getting Internal Server Error whenever I try adding the password to the connection.

**Comment by manast** [comment]
Thanks for the report. Which redis provider are you using?

**Comment by manast** [comment]
ok, seems like the password was quite long and this was creating an internal error. This has been resolved now, could you please check it again?

**Comment by TimP4w** [comment]
Sorry for the delay. I'm using a self hosted Redis server on a private machine for development.
I'm still getting the error (yes, the password is 128 chars long).
